title: NWSL, visualized
description: Hi! My name is AJ and I create visualizations of NWSL data. Here, you can find interactive versions of all of the graphics that I have made and shared.
theme: jekyll-theme-minimal
baseurl: "/nwsl-2025"  
