title: NWSL, visualized
subtitle: All posts
description: |
  <a href="nighswonger.html">Jenna Nighswonger: A statistical retrospective -- 1/27/2025</a>
  <a href="schedule.html">NWSL 2025 schedule, visualized -- 1/23/2025</a>
theme: jekyll-theme-minimal
